jujong/jujong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

jujong/movies/urls.py
from django.urls import path
from . import views


app_name= "movies"

urlpatterns =[
    path('', views.main, name="main"),
    path('movieCollect/', views.movieCollect, name="movieCollect"),
    path('<int:id>/', views.detail, name="detail"),
    # path('<int:id>/comment/create/',views.commentCreate, name="commentCreate"),
    # path('<int:id>/comments/<int:comment_id>/delete/', views.commentDelete, name='commentDelete'),
    path('<int:id>/score/create/',views.scoreCreate, name="scoreCreate"),
    path('recommend/', views.recommend2, name="recommend2"),
    path('movie_create/', views.movie_create, name='movie_create'),
    path('<int:movie_pk>/update/', views.movie_update, name='movie_update'),
    path('<int:movie_pk>/delete/', views.movie_delete, name='movie_delete'),
    path('<int:movie_pk>/review_create/', views.review_create, name='review_create'),
    path('<int:movie_pk>/<int:review_pk>', views.review_detail, name='review_detail'),
    path('<int:movie_pk>/<int:review_pk>/review_update/', views.review_update, name='review_update'),
    path('<int:movie_pk>/<int:review_pk>/review_delete/', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/<int:review_pk>/comment_create/', views.comment_create, name='comment_create'),
    path('<int:movie_pk>/<int:review_pk>/<int:comment_pk>/comment_delete/', views.comment_delete, name='comment_delete'),
    path('profile/', views.profile, name= "profile"),
    path('user_management/', views.user_management, name = "user_management"),
    path('search/search_result', views.search_result, name="search_result"),



]

jujong/movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    poster_path = models.CharField(max_length=150)
    tmd_id = models.CharField(max_length=50)
    genres = models.CharField(max_length=100)
    overview = models.TextField()
    release_date = models.CharField(max_length=50)
    backdrop_path = models.CharField(max_length=150)
    director = models.CharField(max_length=100)
    tagline = models.TextField()
    popularity = models.FloatField()
    vote_average = models.FloatField()
    casts = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    rank = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)



class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    
    
class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete = models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField()

jujong/movies/forms.py
from django import forms
from .models import Movie, Comment, Score, Review

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        
class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ['content',]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'rank', 'content']

class SearchForm(forms.ModelForm):
    word = forms.CharField(label='Search Word')

jujong/movies/views.py
from django.shortcuts import render,redirect, get_object_or_404
import requests
from .models import Movie, Comment, Score, Review
from .forms import MovieForm, CommentForm, ReviewForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.db.models import Q
# Create your views here.

# 영화 데이터 수집
def movieCollect(request):

    api_key = '560c0e0b21628cdf0431b39687354675'
    TMDB_URL = 'https://api.themoviedb.org/3/discover/movie'
    
    # 10페이지 정보 받아오기
    for n in range(1, 11):
        num = str(n)
        Movies_URL = f"{TMDB_URL}?api_key={api_key}&language=ko-KR&page={num}" 
        listData = requests.get(Movies_URL).json()
        resDatas = listData['results']
    
        # 한 영화당 detail정보 가져오기
        for resData in resDatas:
            api_key = '560c0e0b21628cdf0431b39687354675'
            Movie_URL = 'https://api.themoviedb.org/3/movie'
            tmd_id = resData.get('id')
            DETAIL_URL = f"{Movie_URL}/{tmd_id}?api_key={api_key}&language=ko-KR"
            detailData = requests.get(DETAIL_URL).json()

            # 배우, 감독 정보 가져오기
            CREDITS_URL = f"{Movie_URL}/{tmd_id}/credits?api_key={api_key}"
            creditsData = requests.get(CREDITS_URL).json()
            # 배우 찾기
            castData = requests.get(CREDITS_URL).json().get('cast')
            casts = []
            for n in range(len(castData)):
                casts.append(castData[n].get('name'))
                if len(casts) > 4:
                    break
            casts = (', ').join(casts)
            
            # 감독 찾기
            crewData = creditsData.get('crew')
            for n in range(len(crewData)):
                if crewData[n].get('job') =='Director':
                    director = crewData[n].get('name')
                    break
                else:
                    director = ""
                   
            # 장르이름 저장하기
            genres = []
            for genre in detailData.get('genres'):
                genres.append(genre.get('name'))
            genres = (', ').join(genres)
            
            # 배경이미지 없을 경우 오류 발생 방지
            if resData.get('backdrop_path'):
                backdrop_path = "https://image.tmdb.org/t/p/original" + resData.get('backdrop_path')
            

            Movie.objects.get_or_create(
                tmd_id = tmd_id,
                title = resData.get('title'),
                backdrop_path = backdrop_path,
                poster_path = "https://image.tmdb.org/t/p/original"+ resData.get('poster_path'),
                overview = detailData.get('overview'),
                release_date = detailData.get('release_date'),
                tagline = detailData.get('tagline'),
                casts = casts,
                director = director,
                genres = genres,
                popularity = detailData.get('popularity'),
                vote_average = detailData.get('vote_average'),
                )

    return redirect('movies:main')


def main(request):
    # Pagination
    movie_list = Movie.objects.all()
    
    paginator = Paginator(movie_list, 20) 
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    context = {
        'movies': movie_list,
        'page_obj': page_obj,
    }
    return render(request, 'movies/main.html', context)
    
    
# 디테일 페이지
def detail(request, id):
    # 영화
    movie = Movie.objects.get(id=id)
    # 리뷰
    reviews = movie.review_set.all()
    # 평점
    ratings = 0
    for score in movie.score_set.all():
        ratings += score.rating
    if ratings == 0:
        ratingAvg = 0
    else:
        ratingAvg = ratings/movie.score_set.all().count()
    ratingAvg = round(ratingAvg,2)

    YOUTUBE_API_KEY='AIzaSyCPSTJXHRJCuhiH16LYXvsFYYKxTSkAzWw'
    
    YOUTUBE_URL = 'https://www.googleapis.com/youtube/v3/search'
    params = {
        'key': YOUTUBE_API_KEY,
        'part': 'snippet',
        'type': 'video',
        'q': movie.title + 'trailer'
    }
    response = requests.get(YOUTUBE_URL, params=params).json()
    # print(response)
    video_id = response['items'][0]['id']['videoId']
    # print(video_id)
    video = f'https://www.youtube.com/embed/{video_id}'

    context = {
        'movie':movie,
        'reviews': reviews, 
        "ratingAvg":ratingAvg,
        'video': video,
    }

    return render(request, 'movies/detail.html', context )

    
# 평점 등록하기
@login_required
def scoreCreate(request, id):
    rating = request.POST.get('rating')
    user = request.user
    movie = Movie.objects.get(id=id)
    score_list = Score.objects.filter(user=user,movie=movie)
    
    if score_list:
        score = score_list.update(rating=rating)
    else:
        score = Score.objects.create(user=user, movie=movie, rating=rating)

    return redirect('movies:detail', id)
  
def movie_create(request):
    if request.user.is_superuser:
        if request.method =='POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                movie = form.save()
                return redirect('movies:main')
        else:
            form = MovieForm()
        context = {
            'form':form,
        }
        return render(request, 'movies/form.html', context)

def movie_update(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method =="POST":
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/form.html', context)


def movie_delete(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    movie.delete()
    return redirect('movies:main')


# 여기
def review_create(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.movie_id = movie.pk
                form.save()
                return redirect('movies:detail', movie.pk)
        else:
            form = ReviewForm()
        context = {
            'form': form
        }
        return render(request, 'movies/form.html', context)
    else:
        return redirect('accounts:login')

def review_detail(request, movie_pk, review_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    review = get_object_or_404(Review, pk=review_pk)
    comments = review.comment_set.all()
    form = CommentForm()
    context = {
        'movie': movie,
        'review': review,
        'form': form,
        'comments':comments,
    }
    return render(request, 'movies/review_detail.html', context)


def review_update(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method =="POST":
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('movies:review_detail', movie_pk, review_pk)
    else:
        form = ReviewForm(instance=review)
    context = {
        'form': form,
        'review': review,
    }
    return render(request, 'movies/form.html', context)


def review_delete(request, movie_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    review.delete()
    return redirect('movies:detail', movie_pk)


def comment_create(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                form = form.save(commit=False)
                form.user = request.user
                form.review_id = review.pk
                form.save()
        return redirect('movies:review_detail', movie_pk, review.pk)
    else:
        return redirect('accounts:login')

@require_POST
def comment_delete(request, movie_pk, review_pk, comment_pk):
    if request.method=="POST":
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:review_detail', movie_pk, review_pk)


def recommend2(request):
    user = request.user
    movies = Movie.objects.order_by('-popularity')
    result = movies
    api_key = '560c0e0b21628cdf0431b39687354675'
    result2 = []

    if request.user.is_authenticated:
        like_list = []
        like_genres_list = []
        for like_movie in Score.objects.filter(user=user, rating__gte=4).order_by('-rating'):
            id = like_movie.movie
            like_list.append(id)     
            like_genres = id.genres.split(', ')
        like_genres_list.extend(like_genres)

        result_title = []
        for genre in like_genres_list:
            for movie in movies:
                if genre in movie.genres and movie not in like_list and movie.title not in result_title:
                    result2.append(movie)
                    result_title.append(movie.title)

    recommend_URL = f'https://api.themoviedb.org/3/movie/{like_list[-1].tmd_id}/recommendations?api_key={api_key}&language=ko-KR&page=1'
    recommend_list = requests.get(recommend_URL).json()['results']
    recommend_movies = []
    recommend_title = []

    for recommend_movie in recommend_list:
        for movie in movies:
            if recommend_movie['title'] == movie.title and movie.title not in recommend_title:
                recommend_movies.append(movie)
                recommend_title.append(movie.title)

jujong/movies/templates/movies/detail.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block content %}
    <div class="container text-white" style="font-family: 'Gamja Flower', cursive;">
        <!-- 배경 이미지 -->
        <div class="fontchange">
            <div class="col-12 p-0">
            <img src="{{ movie.backdrop_path }}" style="width:100%; height:500px; opacity:0.8"   />
            </div>
        <!--영화 제목-->
        <div class="pt-1">
            <span style="font-size:45px"><b>{{ movie.title }}</b></span> | 
            <span style="font-size:25px"><b>{{ movie.tagline }}</b></span> |
        </div>
        <hr>
        <!--영화 정보-->
        <div class="row" style="background-color: black;">
            <!--영화 이미지-->
            <div class="col-md-4 d-flex my-3">
                <img src="{{movie.poster_path}}"  style="width:100%; height:100%" />
            </div>
            <!--영화 정보-->
            <div class="col-md-8 d-flex my-5">
                <div style="font-size: 22px;">
                    <h4 class="mr-3">장르: {{ movie.genres }}</h4>
                    {% if movie.director %}
                        <h4 class="mr-3">감독: {{ movie.director }}</h4>
                    {% else %}
                    {% endif %}
                    <h4 class="mr-3">출연진: {{ movie.casts }}</h4>
                    <h4 class="mr-3">개봉일: {{ movie.release_date }}</h4>
                    <h4 class="mr-3">평점: {{ movie.vote_average }}</h4>
                    <h4 class="mr-3">인기도: {{ movie.popularity }}</h4>
                    <hr>
                    <h5 class="mr-3">줄거리</h5>
                    <p> {{ movie.overview }}</p>
                    

                    {% if user.is_superuser %}
                        <a href="{% url 'movies:movie_update' movie.pk %}">글 수정</a>
                        <a href="{% url 'movies:movie_delete' movie.pk %}">글 삭제</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <hr>
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" type="text/html" src="{{ video }}" frameborder="0"></iframe>
        </div>
        <!-- 평점 -->
            {% if movie.score_set.all.count %}
                <h3>이 영화에 대한 평점은 {{ ratingAvg }}점 입니다.</h3>
                <h3>지금까지 이 영화에 {{movie.score_set.all.count}}분이 평가를 해주셨어요! &nbsp; </h3>
            {% else %}
                <h3>이 영화에 대한 별점이 없어요. 처음으로 평가를 남겨보세요! &nbsp; </h3>
            {% endif %}
            {% if user.is_authenticated %}
                {% for score in movie.score_set.all %}
                    {% if score.user == request.user %}
                        <h4><b>{{score.user.username}}</b>님의 별점 {{score.rating}}점</h4>
                    {% endif %}
                {% endfor %}
                <!--별점 입력-->
                <form action="{% url 'movies:scoreCreate' movie.id %}" method="POST">
                    {% csrf_token %}
                    <select name="rating" id="rating">
                        <option value="1">★☆☆☆☆</option>
                        <option value="2">★★☆☆☆</option>
                        <option value="3">★★★☆☆</option>
                        <option value="4">★★★★☆</option>
                        <option value="5">★★★★★</option>
                    </select>
                    <input type="submit" value="별점주기" class="btn btn-secondary btn-sm">
                </form>
            {% endif %}
    
        <hr>
        <!-- 댓글 -->
        {% if reviews %}
            <p style="font-size: 20px;">지금까지 이 영화에 {{movie.review_set.all.count}}개의 Review가 있어요!</p>
        {% else %}
            <p style="font-size: 20px;">이 영화에 대한 댓글이 없어요. 한줄평을 써보는건 어떠신가요?</p>
        {% endif %}
        <div>
            <table class="table table-hover mt-3">
              <thead class="thead-dark">
                <tr style="font-size: 25px;">
                  <th scope="col" width='10%'>#</th>
                  <th scope="col" width='30%'>TITLE</th>
                  <th scope="col" width='30%'>CONTENT</th>
                  <th scope="col" width='10%'>RANK</th>
                  <th scope="col" width='20%'>CREATED_TIME</th>
                </tr>
              </thead>
              <tbody class ="text-white" style="font-size: 20px;">
                {% for review in reviews %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href="{% url 'movies:review_detail' movie.pk review.pk %}" class="text-reset">{{ review.title }}</a></td>
                      <td>{{ review.content|truncatewords:3 }}</td>
                      <td>{{ review.rank }}</td>
                      <td>{{ review.created_at }}</td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
            {% if user.is_authenticated %}
                <a href="{% url 'movies:review_create' movie.pk %}" style="font-size: 25px;">리뷰 작성</a>
            {% endif %}
        </div>
    </div>    
{% endblock %}

jujong/movies/templates/movies/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}
    <form action="" method ="POST" class="text-white">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button>입력</button>
    </form>

{% endblock %}

jujong/movies/templates/movies/main.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap_pagination %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% if movies.has_previous %}
  {% else %}
    <iframe allow="autoplay" width="100%" height="570" src="https://www.youtube.com/embed/Y42i_Q_n9wQ?autohide=0&autoplay=0&mute=0&controls=0&disablekb=1&modestbranding=1&rel=0&showinfo=0" frameborder="0" allowfullscreen></iframe>
  {% endif %}
    <!--영화 목록-->

    <div class="container">
        
        <h2 class="text-center mt-5 text-white" style="font-family: 'Gamja Flower', cursive;"><b>전체 영화 목록</b></h2>

        <br><br><br>
        {% if user.is_authenticated %}
        <a href="{% url 'movies:recommend2' %}" class="d-flex justify-content-end">
            <button type="button" class="btn btn-danger">영화 추천 받기</button>
        </a>
        {% endif %}
        <div class="row border border-dark my-3">
        {% for movie in page_obj %}
            <div class="col-md-4 col-lg-3 my-3" >
                <div class="card d-flex justify-content-center mt-4">  
                    <a href="{% url 'movies:detail' movie.id %}">                    
                        <img src="{{movie.poster_path}}" class="card-img-top" alt="..." id="mainImg" >
                    </a>
                </div>
                <div class="card-body">
                    <h6 class="card-title text-center text-white" style="font-family: 'Gamja Flower', cursive; font-size: 23px;" ><strong>{{movie.title|truncatechars:15}}</strong></h6>
                    <hr>
                </div>
            </div>
        {% endfor %}
        </div>
        
        <!--pagination-->
        <div class="d-flex justify-content-center">
            {% bootstrap_paginate page_obj range=5 show_prev_next="false" show_first_last="true" %}
        </div>
    </div>
    </div>

{% endblock %}

jujong/movies/templates/movies/profile.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}


{% block content %}
<div style="font-family: 'Gamja Flower', cursive;">
    <h1 class = "text-white">{{ user }}님의 히스토리</h1>
    <hr>
    <h2></h2>
    <div class ="row">
        <div class="card-deck ">

            {% for movie, rate in my_rates_list %}
            <div class="col-3">
                <div class="card">
                    <a href="{% url 'movies:detail' movie.id %}">
                        <img src="{{ movie.poster_path }}" class="card-img-top" alt="...">
                    </a>
                    <div class="card-body " style="padding-bottom: 0px; background-color: powderblue;">
                        <p class=" d-flex card-title justify-content-between" style="font-size: 25px;"> <span>{{ movie.title |truncatechars:10 }}</span> <span>{{ rate }} 점</span> </p>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>





{% endblock %}

jujong/movies/templates/movies/recommend.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}


{% block content %}


<h1 class="text-white" style="font-family: 'Gamja Flower', cursive;">같은 장르의 이런 영화 어떠세요?</h1>
<div>
  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <div class ="row">
          {% for movie in like_movies1 %}
          <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
            <img src="{{ movie.poster_path }}" class="d-block w-100 h-100" alt="poster">
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="carousel-item">
        <div class ="row">
          {% for movie in like_movies2 %}
          <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
              <img src="{{ movie.poster_path }}" class="d-block w-100 h-100" alt="poster">
            </a>
          </div>
        {% endfor%}
        </div>
      </div>
      <div class="carousel-item">
        <div class ="row">
          {% for movie in like_movies3 %}
          <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
              <img src="{{ movie.poster_path }}" class="d-block w-100 h-100" alt="poster">
            </a>
          </div>
        {% endfor%}
        </div>
      </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<hr>

<h1 class="text-white" style="font-family: 'Gamja Flower', cursive;">{{ request.user}} 님께 추천 드리는 영화</h1>
<div>
  <div id="r_carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <div class ="row">
          {% for movie in rec_movies1 %}
          <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
              <img src="{{ movie.poster_path }}" class="d-block w-100 h-100" alt="poster">
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="carousel-item">
        <div class ="row">
          {% for movie in rec_movies2 %}
          <div class="col-md-3">
            <a href="{% url 'movies:detail' movie.id %}">
              <img src="{{ movie.poster_path }}" class="d-block w-100 h-100" alt="poster">
            </a>
          </div>
        {% endfor%}
        </div>
      </div>


    </div>




    <a class="carousel-control-prev" href="#r_carouselExampleFade" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#r_carouselExampleFade" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

{% endblock %}

jujong/movies/templates/movies/review_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class ="container">
    <div class= "row">
        <div class = "col-8 text-white" style="font-family: 'Gamja Flower', cursive; font-size: 22px;">
            <h2>{{ review.user }}의 리뷰</h2>
            <hr>
            <h2>제목 : {{ review.title }}</h2>
            <hr >
            <p>내용 : {{ review.content }}</p>
            <hr>
            {% if request.user == review.user %}
                <a href="{% url 'movies:review_update' movie.pk review.pk %}">수정</a>
                <a href="{% url 'movies:review_delete' movie.pk review.pk %}">삭제</a>
            {% endif %}
            <a href="{% url 'movies:detail' movie.pk %}">돌아가기</a>
        </div>
        <div class = "col-4">
            <img src="{{movie.poster_path}}"  style="width:250px; height:300px;">
        </div>
    </div>
    <div class = "text-white" style="font-family: 'Gamja Flower', cursive; font-size: 22px;">
        <hr>
        <h3>댓글목록</h3>
        {% for comment in comments %}
            <hr>
            <p>{{ comment.user }}: {{ comment.content }} | {{ comment.created_at }}</p>
            {% if request.user == comment.user %}
            <form action="{% url 'movies:comment_delete' movie.pk review.pk comment.pk %}" method="POST">
                {% csrf_token %}
                <button>댓글 삭제</button>
            </form>
            {% endif %}
        {% endfor %}
        <form action="{% url 'movies:comment_create' movie.pk review.pk %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button class="btn btn-primary">댓글 작성</button>
        </form>
    </div>
</div>


{% endblock %}

jujong/movies/templates/movies/search_result.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
  <div class="my-3">
    <h2><b>{{ query }}</b>에 대한 검색 결과입니다.</h2>
  </div>
  <div class="row">
    {% for movie in movies %}
      <div class="card col-3">
        <a href="{% url 'movies:detail' movie.pk %}"><img class="card-img-top" src="{{ movie.backdrop_path }}" alt=""></a>
        <div class="card-body">
          <h5 class="card-title">{{ movie.title }}</h5>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

jujong/movies/templates/movies/user_management.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% load static %}
{% block content %}

<div class="text-white">
    <h2>유저 권한 설정</h2>

    {% for user in users %}
        {% if not user.is_superuser %}
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
            <label class="form-check-label" for="inlineCheckbox1">{{ user }}</label>
        </div>
        {% endif %}
    {% endfor %}
    <button class="btn btn-primary">확인</button>

</div>


{% endblock %}